# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 43edede4b06fbec2ef707828d9422224c4eb3abda94cae63bdd70889b901b78df151100819b2e6625bb27ce45f94af7ca9d99ab322de97860e2e1f9dacbb3c6d

test:
  secret_key_base: 4e41ad6f5946f1fab95c816feb32024c8819bcf435b741cc3d1a8118030c229fca48f4cdf162e0a189936b766bdff5810393659aba79f46d4bf94227d1eba4fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
